version: '3.0'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./opfe-bo:/var/www/html
    networks:
      - net
    depends_on:
      - api
      - web-admin
      - web-aff
      - web-member

  api:
    image: php:7.4-fpm-pdo
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    #restart: unless-stopped
    volumes:
      - ./opbackend_tf:/var/www/html
      - ./php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    environment:
      - APPLICATION_ENV=development   #value = staging / production
    networks:
      - net

  web-admin:
    image: php:7.4-fpm-pdo
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web-admin
    #restart: unless-stopped
    volumes:
      - ./opfe-bo:/var/www/html
      - ./php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    environment:
      - APPLICATION_ENV=development   #value = staging / production
    expose:
      - 9000
    networks:
      - net
    extra_hosts:
      - "local.admin.opbackend.com:host-gateway" #admin api

  web-aff:
    image: node:18.16
    container_name: web-aff
    #restart: unless-stopped
    networks:
      - net
    ports:
      - "3000:3000"
    extra_hosts:
      - "local.aff.siam66.com:host-gateway"
    working_dir: /app/aff
    volumes:
      - ./opfe-aff-nuxt/aff:/app/aff
    command: sh -c "npm install && npm run deploy"
    environment:
      - npm_config_project=siam66    #merchant code, not sure check with FE
      - npm_config_env=stage         #value = dev/ stage / prod

  web-member:
    image: node:18.16
    container_name: web-member
    #restart: unless-stopped
    networks:
      - net
    ports:
      - "3001:3000"
    extra_hosts:
      - "local.member.siam66.com:host-gateway"
    working_dir: /app/web
    volumes:
      - ./template_asia_fe/web:/app/web
    command: sh -c "npm install && npm run deploy"
    environment:
      - npm_config_project=siam66   #merchant code, not sure check with FE
      - npm_config_env=stage        #value = stage / prod

networks:
  net:
   driver: bridge
